impl CPU {
    fn ADC() -> u8 {}
    fn AND() -> u8 {}
    fn ASL() -> u8 {}
    fn BBR() -> u8 {}
    fn BBS() -> u8 {}
    fn BCC() -> u8 {}
    fn BCS() -> u8 {}
    fn BEQ() -> u8 {}
    fn BIT() -> u8 {}
    fn BMI() -> u8 {}
    fn BNE() -> u8 {}
    fn BPL() -> u8 {}
    fn BRA() -> u8 {}
    fn BVC() -> u8 {}
    fn BVS() -> u8 {}
    fn CLC() -> u8 {}
    fn CLD() -> u8 {}
    fn CLI() -> u8 {}
    fn CLV() -> u8 {}
    fn CMP() -> u8 {}
    fn CPX() -> u8 {}
    fn CPY() -> u8 {}
    fn DEC() -> u8 {}
    fn DEX() -> u8 {}
    fn EOR() -> u8 {}
    fn INC() -> u8 {}
    fn INX() -> u8 {}
    fn INX() -> u8 {}
}